Repository apache/skywalking-rover, pull requests merged in 2024-11, with the labels that each got.

#151 Separate multiple process for reading connection information in the access log module
  CHANGES.md
  configs/rover_configs.yaml
  pkg/accesslog/collector/connect.go
  pkg/accesslog/common/config.go
Labels: enhancement

#153 Remove unnecessary generic parameters
  pkg/profiling/continuous/checker/common/http_checker.go
  pkg/profiling/continuous/checker/network_error_rate.go
  pkg/profiling/continuous/checker/network_response_time.go
Labels: chore

#154 Refactor the socket detail message in the Access log module
  pkg/accesslog/collector/protocols/http1.go
  pkg/accesslog/collector/protocols/http2.go
  pkg/accesslog/collector/protocols/protocol.go
  pkg/accesslog/collector/protocols/queue.go
  pkg/accesslog/common/connection.go
  pkg/accesslog/common/queue.go
  pkg/accesslog/events/detail.go
  pkg/accesslog/forwarder/close.go
  pkg/accesslog/forwarder/connect.go
  pkg/accesslog/forwarder/forwarder.go
  pkg/accesslog/forwarder/protocol.go
  pkg/accesslog/forwarder/transfer.go
Labels: chore

#155 Add a delay time before delete the connection in the access log module
  CHANGES.md
  pkg/accesslog/collector/connect.go
  pkg/accesslog/collector/protocols/http1.go
  pkg/accesslog/collector/protocols/queue.go
  pkg/accesslog/common/connection.go
  pkg/profiling/task/network/analyze/layer7/events.go
  pkg/tools/btf/queue.go
  test/e2e/cases/profiling/task/network/http2/go.sum
Labels: enhancement

#158 Add a dead link checker for Documentation in the CI
  .dlc.json
  .github/workflows/dead-link-checker.yaml
  .licenserc.yaml
  CHANGES.md
  README.md
  docs/en/concepts-and-designs/module_design.md
  docs/en/guides/contribution/how-to-write-module.md
  docs/en/setup/configuration/service-discovery.md
Labels: documentation

#157 Fix context structs parameters for tracepoint programs
  bpf/accesslog/l24/read_l2.c
  bpf/accesslog/l24/write_l2.c
  bpf/accesslog/l24/write_l4.c
  bpf/accesslog/process/process.c
  bpf/accesslog/syscalls/close.c
  bpf/accesslog/syscalls/connect.c
  bpf/accesslog/syscalls/transfer.c
  bpf/include/api.h
Labels: enhancement

#159 Improve the build of skywalking-rover
  CHANGES.md
  docker/Dockerfile.build
  docker/Dockerfile.debug
  scripts/build/build.mk
Labels: enhancement

#160 Support analyze multiple protocol in the same connection
  pkg/accesslog/collector/protocols/connection.go
  pkg/accesslog/collector/protocols/http1.go
  pkg/accesslog/collector/protocols/http2.go
  pkg/accesslog/collector/protocols/queue.go
  pkg/accesslog/events/data.go
  pkg/profiling/task/network/analyze/events/data.go
  pkg/profiling/task/network/analyze/layer7/protocols/protocols.go
  pkg/tools/buffer/buffer.go
  pkg/tools/ssl/gotls.go
Labels: enhancement
