Repository apache/skywalking-rover, pull requests merged in 2024-03, with the labels that each got.

#115 Upgrade eBPF, Go library and adapt GHA
  .github/workflows/compatibility.yaml
  .github/workflows/rover.yaml
  .gitignore
  .golangci.yml
  CHANGES.md
  bpf/include/socket.h
  bpf/profiling/continuous/network.c
  bpf/profiling/network/sock_stats.h
  docker/Dockerfile.base
  go.mod
  go.sum
  pkg/profiling/task/network/analyze/base/connection.go
  pkg/tools/btf/linker.go
  pkg/tools/process/process.go
  scripts/build/base.mk
  scripts/build/lint.mk
Labels: enhancement

#119 Adjust documentation
  CHANGES.md
  docs/en/concepts-and-designs/architecture.png
  docs/en/concepts-and-designs/module_design.md
  docs/en/concepts-and-designs/overview.md
  docs/en/concepts-and-designs/project_structue.md
  docs/en/setup/configuration/common.md
  docs/en/setup/configuration/logger.md
  docs/en/setup/configuration/profiling.md
  docs/en/setup/configuration/service-discovery.md
  docs/en/setup/configuration/traffic.md
  docs/en/setup/deployment/kubernetes/readme.md
  docs/en/setup/deployment/kubernetes/rover-daemonset.yml
  docs/en/setup/overview.md
  docs/menu.yml
Labels: documentation

#120 Fix release script path
  scripts/build/release.mk
Labels: bug

#121 Polish docs
  docs/en/setup/overview.md
  docs/menu.yml
Labels: documentation
